export interface PropertyDetails {
	additionalCosts: number;
	address: string;
	bathroom: boolean;
	city: string;
	energyLabel: string;
	furnished: boolean;
	internet: boolean;
	kitchen: boolean;
	living: boolean;
	matchDaytimeActivity: any;
	matchGender: any;
	matchLanguage: any;
	matchMaxAge: number;
	matchMinAge: number;
	matchPeople: number;
	pets: boolean;
	postalCode: string;
	propertyType: any;
	publicationDate: Date;
	registrationCosts: number;
	rent: number;
	rentableFrom: Date;
	rentableTo: Date;
	savings: number;
	smoking: boolean;
	surface: number;
	utilities: boolean;
}